# Generated by Django 3.1 on 2020-11-17 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('visitor_id', models.IntegerField(primary_key=True, serialize=False)),
                ('visitor_name', models.CharField(max_length=100)),
                ('visitor_type', models.CharField(choices=[('O', 'Other'), ('L', 'Lawyer'), ('F', 'Family or Friends')], default='O', max_length=1)),
                ('associated_prisoners', models.ManyToManyField(related_name='prisoners', to='prison.Prisoner')),
            ],
        ),
    ]
