# Generated by Django 3.1 on 2020-11-17 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0002_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='associated_prisoners',
            field=models.ManyToManyField(to='prison.Prisoner'),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('L', 'Lawyer'), ('O', 'Other'), ('F', 'Family or Friends')], default='O', max_length=1),
        ),
    ]
