# Generated by Django 3.1 on 2021-01-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prison', '0003_auto_20201117_1158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='visitor_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='visitor',
            name='visitor_type',
            field=models.CharField(choices=[('L', 'Lawyer'), ('F', 'Family or Friends'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
